### ISSUE TITLE
Error on ydb.open(); YottaDB database connection cannot be reopened

### ISSUE THREAD

**Issue by faisalsami** [dlwicksell/nodem#14]
Is there any way we can check if the database connection is already established. Thanks

**Comment by dlwicksell** [comment]
Yes, there are a couple ways to handle this. First, if the database connection hasn't been opened, then the Nodem APIs will return with an exception, which you could catch in a _try/catch_ statement, and then _open_ the connection to the database before using the APIs, e.g.

```javascript
> const nodem = require('nodem').Ydb();
undefined
> nodem.get('^global');
Uncaught Error: YottaDB connection is not open
> try {
... nodem.get('^global');
... } catch (err) {
... nodem.open();
... nodem.get('^global');
... }
1000
```
Second, the _version_ API only reports the version of the underlying YottaDB or GT.M system, when the database connection has been opened, so you could search for the substring 'YottaDB Version' (or 'GT.M Version' when using GT.M), in the output of the _version_ API, to determine if there is a current database connection, e.g.

```javascript
> const nodem = require('nodem').Ydb();
undefined
> nodem.version();
'Node.js Adaptor for YottaDB: Version: 0.20.0 (ABI=93) [FWS]'
> nodem.version().includes('YottaDB Version');
false
> nodem.open();
{ ok: true, pid: 86593, tid: 86593 }
> nodem.version();
'Node.js Adaptor for YottaDB: Version: 0.20.0 (ABI=93) [FWS]; YottaDB Version: 1.32'
> nodem.version().includes('YottaDB Version');
true
```
I hope that helps! I'm going to close this issue, as I believe I have addressed it sufficiently. Thank you.

**Comment by faisalsami** [comment]
Yes that helps a lot thank you
